export const AvDatePickerStub = defineComponent({
  name: 'AvDatePicker',
  props: {
    id: String,
    ariaLabel: String,
    clearLabel: String,
    label: String,
    labelClass: String,
    labelVisible: Boolean,
    errorMessage: [String, Array],
    type: String,
    modelValue: [Date, Object, Array],
    width: String,
    minDate: [Date, String, Number],
    maxDate: [Date, String, Number],
    disabled: Boolean,
    placeholder: String,
    locale: [String, Object],
    autoApply: Boolean,
    inputAttrs: Object,
    formats: Object,
    timeConfig: Object,
  },
  emits: ['update:modelValue', 'change'],
  template: `<div class="av-date-picker-stub" data-testid="av-date-picker-stub" />`,
})
