export const AvInputStub = defineComponent({
  name: 'AvInput',
  props: {
    modelValue: String,
    label: String,
    labelClass: String,
    placeholder: String,
    isValid: Boolean,
    isTextarea: Boolean,
    labelVisible: Boolean,
    disabled: Boolean,
    required: Boolean,
    maxlength: Number,
    minlength: Number,
    errorMessage: String,
    validMessage: String,
    maxlengthExceededMessage: String,
    prefixIcon: String,
    id: String,
    descriptionId: String,
    hint: String,
    type: String,
    minDate: String,
    maxDate: String,
    width: String,
    noRadius: Boolean,
    modelModifiers: Object,
    textareaMinHeight: String,
    formatDateStr: String,
    ariaLabel: String,
    dataTestid: String,
  },
  emits: ['update:modelValue'],
  template: '<div><input @input="$emit(\'update:modelValue\', $event.target.value)" :data-testid="dataTestid || \'av-input-stub\'" :aria-label="ariaLabel" :value="modelValue" :placeholder="placeholder" :disabled="disabled" :required="required" :maxlength="maxlength" /><slot name="requiredTip" /><slot name="maxLengthCaption" :current-value="modelValue" /><slot name="suffix" /></div>'
})
