name: Autodeploy to npm (no need to run it)

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  publish-to-npm:
    uses: avenirs-esr/avenirs-workflows/.github/workflows/auto-deploy-to-npm-workflow.yaml@feat/539-frontend-workflows
    secrets: inherit
