name: Auto-deploy Docs + Storybook (no need to run it)

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    uses: avenirs-esr/avenirs-workflows/.github/workflows/frontend-deploy-docs-workflow.yaml@main
    secrets: inherit
