name: PR Quality Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
      - main

jobs:
  run-code-quality-checks:
    uses: avenirs-esr/avenirs-workflows/.github/workflows/frontend-quality-check-workflow.yaml@feat/539-frontend-workflows
    secrets: inherit

  run-a11y-test-and-deploy-reports:
    uses: avenirs-esr/avenirs-workflows/.github/workflows/a11y-test-and-deploy-reports-workflow.yaml@feat/539-frontend-workflows
    with:
      build-command: npm run storybook:build
    secrets: inherit
