name: Generate deploy Key

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
      - main

jobs:
  generate-key:
    runs-on: ubuntu-latest
    steps:
      - name: Generate SSH key
        run: |
          ssh-keygen -t ed25519 -C "avenirs-dsav-bot[bot]@users.noreply.github.com" -f ci_deploy_key -N ""
          echo "Clé publique :"
          cat ci_deploy_key.pub
          echo "Clé privée (à copier dans un secret GitHub) :"
          cat ci_deploy_key