name: Release new version to npm

on:
  workflow_dispatch:
    inputs:
      bump:
        description: Type of version bump
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write

jobs:
  release:
    uses: avenirs-esr/avenirs-workflows/.github/workflows/release-version-to-npm-workflow.yaml@feat/539-frontend-workflows
    secrets: inherit
